name: Say hello in main

on:
  push:
    branches:
      - main
jobs:
  hello_world_main:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo Messagge
        run: |
          echo "Hello, World!!"
      - name: Dime la fecha
        run: date
      - name: View Directory
        run: ls -l
